version: "3.8"

services:
  django:
    # Build from the Dockerfile in the current directory (backend/)
    build: .
    container_name: gbc-django
    # You might not need to mount the volume in production, depends on deploy strategy
    # volumes:
    #   - .:/app
    expose:
      - "8000"
    # Pass environment variables from the .env file
    env_file:
      - .env

  nginx:
    # Build from the Dockerfile in the nginx/ subdirectory
    build: ./nginx
    container_name: gbc-nginx
    ports:
      - "80:80"
      - "443:443" # Expose port 443 for HTTPS
    volumes:
      # Mount Let's Encrypt certificate directory (read-only recommended)
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # Mount Certbot challenge directory (read-write needed for cert generation/renewal)
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - django
