# Generated by Django 5.2 on 2025-05-04 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_id_alter_schedule_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='schedules',
        ),
    ]
