# Generated by Django 5.2 on 2025-05-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_table_alter_schedule_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fees',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
